cc_library(
    name="find_digits",
    srcs=["find_digits.cpp"],
    hdrs=["find_digits.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="append_and_delete",
    srcs=["append_and_delete.cpp"],
    hdrs=["append_and_delete.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="sherlock_and_squares",
    srcs=["sherlock_and_squares.cpp"],
    hdrs=["sherlock_and_squares.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="library_fine",
    srcs=["library_fine.cpp"],
    hdrs=["library_fine.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="non_divisible_subset",
    srcs=["non_divisible_subset.cpp"],
    hdrs=["non_divisible_subset.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="jumping_on_clouds",
    srcs=["jumping_on_clouds.cpp"],
    hdrs=["jumping_on_clouds.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="acm_icpc_team",
    srcs=["acm_icpc_team.cpp"],
    hdrs=["acm_icpc_team.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="taum_bday",
    srcs=["taum_bday.cpp"],
    hdrs=["taum_bday.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="organizing_containers",
    srcs=["organizing_containers.cpp"],
    hdrs=["organizing_containers.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="encryption",
    srcs=["encryption.cpp"],
    hdrs=["encryption.hpp"],
    visibility=["//test:__pkg__"],
)

cc_library(
    name="bigger_is_greater",
    srcs=["bigger_is_greater.cpp"],
    hdrs=["bigger_is_greater.hpp"],
    visibility=["//test:__pkg__"],
)
